sudo: required
services:
  - docker
before_install:
  - cd frontend
  - docker build -f Dockerfile.dev -t grimmauld/docker-udemy .
script:
  - docker run -e CI=true grimmauld/docker-udemy npm run test