apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadate:
  name: grimmauld-org-tls
spec:
  secretName: grimmauld-org
  issuerRef: 
    name: letsencrypt-prod
  kind: ClusterIssuer
  commonName: grimmauld.org
  dnsNames:
    - grimmauld.org
    - www.grimmauld.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - grimmauld.org
          - www.grimmauld.org
